Remove ununsed 'using namespace std'
This causes build error on clang-r522817 + new libc++:

In file included from hardware/ril/libril/RilSapSocket.cpp:20:
In file included from hardware/ril/libril/RilSapSocket.h:21:
In file included from hardware/ril/libril/RilSocket.h:20:
hardware/ril/libril/rilSocketQueue.h:22:17: error: using directive refers to implicitly-defined namespace 'std' [-Werror]
   22 | using namespace std;
      |                 ^
1 error generated.

Test: presubmit
Bug: 322868540
Change-Id: I14ab941c7d04947d5d8fe675d4451ee1f7fbc4ea